package constants;

import java.io.Serializable;

public enum RequestCode implements Serializable {
    LOGIN_REQUEST,
    SIGNUP_REQUEST,
    ADMIN_LOGIN_REQUEST,
    STAFF_REGISTER_REQUEST,
    DOCTOR_LOGIN_REQUEST,
    STAFF_LOGIN_REQUEST,
    CHANGE_PASSWORD_REQUEST,
    BED_REQUEST,
    BLOOD_BANK_REQUEST,
    APPOINTMENT_REQUEST,
    DOCTOR_AVAILABILITY_REQUEST,
    ATTENDANCE_REQUEST,
    USER_LEAVE_REQUEST,
    VACCINE_AVAILABILITY_REQUEST,
    VACCINATION_REQUEST,
    LOGOUT_REQUEST,
    PATIENT_REQUEST,
    GET_DOCTORS_REQUEST,
    GET_STAFF_REQUEST,
    TIMETABLE_REQUEST,
    SCHEDULE_REQUEST;

    @Override
    public String toString() {
        return this.name();
    }
}
